spring.jms.listener.auto-startup=true
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=artemis
spring.activemq.password=artemis

applicationinsights.connection.string=InstrumentationKey=20d3388c-a103-4946-9260-8a489e90113a;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=bb37964b-c62d-4fc7-bee5-cf57b5d23735